******************************************************
2019-11-08 14:12:02,746 - INFO - logger - Path for logging: data/outputs/20191108131148\micro_grid_design_logfile.log
2019-11-08 14:12:02,747 - INFO - logger - Used oemof version: 0.2.2
2019-11-08 14:12:02,748 - INFO - A_offgridders_wrapper - 
 
 MICRO GRID TOOL 3.0
 Version: 19.06.2019 
 Coded by: Martha M. Hoffmann 
 Reiner Lemoine Institute (Berlin) 
 
 
2019-11-08 14:12:02,752 - INFO - C_sensitivity_experiments - Parameters of sensitivity analysis
2019-11-08 14:12:02,755 - INFO - C_sensitivity_experiments - Randomized blackout timeseries for all combinations of blackout duration and frequency (1 experiments) will be generated.
2019-11-08 14:12:02,949 - DEBUG - C_sensitivity_experiments - Generating header for results.csv
2019-11-08 14:12:03,006 - INFO - C_sensitivity_experiments - For 1 project sites with 1 scenarios each, 1 sensitivity_experiment_s will be performed for each case.
2019-11-08 14:12:03,026 - INFO - E_blackouts_central_grid - Blackout experiment 1: Blackout duration 2.5 hrs, blackout frequency 4 per month
2019-11-08 14:12:03,028 - INFO - E_blackouts_central_grid - Number of blackouts in simulated timeframe: 48
2019-11-08 14:12:03,043 - DEBUG - E_blackouts_central_grid - Blackouts events occur on following dates: 2019-01-01 04:00:00, 2019-01-01 13:00:00, 2019-01-08 11:00:00, 2019-01-24 11:00:00, 2019-01-29 15:00:00, 2019-02-17 06:00:00, 2019-03-10 05:00:00, 2019-03-13 23:00:00, 2019-03-16 04:00:00, 2019-03-19 13:00:00, 2019-03-21 10:00:00, 2019-03-25 10:00:00, 2019-04-07 18:00:00, 2019-04-09 14:00:00, 2019-04-14 23:00:00, 2019-04-27 01:00:00, 2019-05-02 12:00:00, 2019-05-05 23:00:00, 2019-05-08 15:00:00, 2019-05-26 03:00:00, 2019-06-01 03:00:00, 2019-06-02 18:00:00, 2019-06-12 00:00:00, 2019-06-13 02:00:00, 2019-06-30 16:00:00, 2019-07-15 13:00:00, 2019-08-18 05:00:00, 2019-08-29 10:00:00, 2019-08-31 14:00:00, 2019-09-05 06:00:00, 2019-09-07 17:00:00, 2019-09-10 13:00:00, 2019-09-15 20:00:00, 2019-09-25 08:00:00, 2019-10-04 16:00:00, 2019-10-07 01:00:00, 2019-10-12 11:00:00, 2019-10-15 12:00:00, 2019-10-31 12:00:00, 2019-11-04 13:00:00, 2019-11-22 13:00:00, 2019-11-23 19:00:00, 2019-11-24 08:00:00, 2019-12-01 23:00:00, 2019-12-09 02:00:00, 2019-12-14 08:00:00, 2019-12-14 12:00:00, 2019-12-18 00:00:00
2019-11-08 14:12:03,044 - INFO - E_blackouts_central_grid - Accumulated blackout duration: 120.0
2019-11-08 14:12:03,044 - INFO - E_blackouts_central_grid - Accumulated blackout duration (rounded to timestep): 96.0
2019-11-08 14:12:05,468 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:05] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:12:08,523 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:08] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:12:08,686 - INFO - E_blackouts_central_grid - Grid is not operational for 96 hours, with a reliability of 98.9 percent. 

2019-11-08 14:12:08,688 - INFO - E_blackouts_central_grid - Missing blackout timeseries added through auto-generation.
2019-11-08 14:12:08,799 - DEBUG - core - Creating PluginEnvironment 'pca'
2019-11-08 14:12:08,801 - DEBUG - core - Pushing environment 'pca' on the PluginGlobals stack
2019-11-08 14:12:09,664 - DEBUG - core - Pushing environment 'pca' on the PluginGlobals stack
2019-11-08 14:12:09,687 - DEBUG - core - Popping environment 'pca' from the PluginGlobals stack
2019-11-08 14:12:09,690 - DEBUG - core - Pushing environment 'pca' on the PluginGlobals stack
2019-11-08 14:12:11,556 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:11] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:12:13,724 - DEBUG - A_offgridders_wrapper - Using grid availability timeseries that was randomly generated.
2019-11-08 14:12:13,724 - INFO - A_offgridders_wrapper - Starting simulation, project site test_site.
2019-11-08 14:12:13,725 - DEBUG - G1_oemof_create_model - Complete case dictionary:
2019-11-08 14:12:13,725 - DEBUG - G1_oemof_create_model - {'case_name': 'hoevelaken', 'filename': 'hoevelaken', 'total_demand_ac': 365250.00000000105, 'total_demand_dc': 0.0, 'peak_demand': 59.12822150522512, 'evaluated_days': 365, 'genset_with_minimal_loading': False, 'storage_fixed_capacity': None, 'storage_fixed_power': None, 'genset_fixed_capacity': False, 'pv_fixed_capacity': False, 'pcc_consumption_fixed_capacity': False, 'pcc_feedin_fixed_capacity': False, 'wind_fixed_capacity': False, 'rectifier_ac_dc_fixed_capacity': False, 'inverter_dc_ac_fixed_capacity': False, 'allow_shortage': True, 'max_shortage': 0, 'stability_constraint': 'share_hybrid', 'renewable_share_constraint': False, 'number_of_equal_generators': 1, 'evaluation_perspective': 'AC_system', 'force_charge_from_maingrid': False, 'discharge_only_when_blackout': False, 'enable_inverter_only_at_backout': False}
2019-11-08 14:12:13,725 - DEBUG - G1_oemof_create_model - Create oemof model by adding case-specific busses and components.
2019-11-08 14:12:13,727 - DEBUG - G1_oemof_create_model - Added to oemof model: Electricity bus of energy system, AC
2019-11-08 14:12:13,727 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: demand AC
2019-11-08 14:12:13,738 - DEBUG - G1_oemof_create_model - Added to oemof model: Fuel bus
2019-11-08 14:12:13,740 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: source fuel
2019-11-08 14:12:13,742 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: genset oem no minload
2019-11-08 14:12:13,744 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: wind
2019-11-08 14:12:13,747 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: maingrid consumption
2019-11-08 14:12:13,748 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: maingrid feedin
2019-11-08 14:12:13,749 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: pcc consumption oem
2019-11-08 14:12:13,750 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: pcc feedin oem
2019-11-08 14:12:13,752 - DEBUG - G1_oemof_create_model - Added to oemof model: Electricity bus of energy system, DC
2019-11-08 14:12:13,752 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: demand DC
2019-11-08 14:12:13,753 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: pv oem
2019-11-08 14:12:13,755 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: rectifier oem
2019-11-08 14:12:13,755 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: inverter_dc_ac oem
2019-11-08 14:12:13,756 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: excess
2019-11-08 14:12:13,756 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: source shortage
2019-11-08 14:12:13,757 - DEBUG - G1_oemof_create_model - Create oemof model based on created components and busses.
2019-11-08 14:12:14,832 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:14] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:12:17,903 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:17] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:12:21,093 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:21] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:12:24,291 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:24] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:12:27,850 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:27] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:12:31,183 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:31] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:12:34,412 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:34] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:12:37,859 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:37] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:12:39,591 - INFO - G1_oemof_create_model - Added constraint: Stability though actual generation of diesel generators and backup through batteries.
2019-11-08 14:12:41,308 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:41] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:12:43,247 - INFO - G1_oemof_create_model - Simulating...
2019-11-08 14:12:44,823 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:44] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:12:48,058 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:48] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:12:51,260 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:51] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:12:54,474 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:54] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:12:57,631 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:12:57] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:13:00,688 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:00] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:13:03,726 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:03] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:13:06,763 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:06] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:13:09,807 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:09] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:13:12,825 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:12] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:13:15,884 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:15] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:13:18,927 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:18] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:13:22,331 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:22] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:13:23,562 - INFO - models - Optimization successful...
2019-11-08 14:13:23,594 - DEBUG - G1_oemof_create_model - Problem solved
2019-11-08 14:13:25,790 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:25] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:13:29,183 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:29] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:13:30,152 - DEBUG - energy_system - Attributes dumped to: data/outputs/20191108131148/oemof\hoevelaken.oemof
2019-11-08 14:13:30,152 - DEBUG - G1_oemof_create_model - Stored results in data/outputs/20191108131148/oemof/hoevelaken.oemof
2019-11-08 14:13:30,152 - DEBUG - G1_oemof_create_model - Restore the energy system and the results.
2019-11-08 14:13:30,152 - INFO - energy_system - Restoring attributes will overwrite existing attributes.
2019-11-08 14:13:30,199 - DEBUG - energy_system - Attributes restored from: data/outputs/20191108131148/oemof\hoevelaken.oemof
2019-11-08 14:13:30,210 - DEBUG - G3_oemof_evaluate - Evaluate flow: demand
2019-11-08 14:13:30,240 - DEBUG - G3_oemof_evaluate - Evaluate flow: shortage
2019-11-08 14:13:30,273 - DEBUG - G3_oemof_evaluate - Evaluate excess: 
2019-11-08 14:13:30,293 - DEBUG - G3_oemof_evaluate - Evaluate flow: fuel
2019-11-08 14:13:30,293 - DEBUG - G3_oemof_evaluate - Evaluate flow: genset
2019-11-08 14:13:30,303 - DEBUG - G3_oemof_evaluate - Evaluate flow: main grid
2019-11-08 14:13:30,331 - DEBUG - G3_oemof_evaluate - Evaluate flow: wind
2019-11-08 14:13:30,335 - DEBUG - G3_oemof_evaluate - Evaluate flow: pv
2019-11-08 14:13:30,341 - DEBUG - G3_oemof_evaluate - Evaluate flow: storage
2019-11-08 14:13:30,357 - DEBUG - G3_oemof_evaluate - Evaluate flow: rectifier
2019-11-08 14:13:30,362 - DEBUG - G3_oemof_evaluate - Evaluate flow: rectifier
2019-11-08 14:13:30,363 - DEBUG - G3_oemof_evaluate - Evaluate: res share
2019-11-08 14:13:30,363 - DEBUG - G3b_plausability_tests - Plausibility test: Charge/Discharge
2019-11-08 14:13:30,363 - DEBUG - G3b_plausability_tests - Plausibility test: Demand/Supply/Shortage
2019-11-08 14:13:30,825 - DEBUG - G3b_plausability_tests - Plausibility test: Feedin/Consumption
2019-11-08 14:13:30,825 - DEBUG - G3b_plausability_tests - Plausibility test: Grid availability consumption
2019-11-08 14:13:30,825 - DEBUG - G3b_plausability_tests - Plausibility test: Grid availability/Feedin
2019-11-08 14:13:30,825 - DEBUG - G3b_plausability_tests - Plausibility test: Excess/shortage
2019-11-08 14:13:30,825 - DEBUG - G3b_plausability_tests - Plausibility test: Excess/Feedin
2019-11-08 14:13:32,527 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:32] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:13:32,854 - WARNING - G2b_constraints_custom - Stability criterion is strictly not fullfilled, but deviation is less then e6.
2019-11-08 14:13:32,854 - DEBUG - G4_output_functions - Saving flows MG.
2019-11-08 14:13:34,045 - DEBUG - _base - update_title_pos
2019-11-08 14:13:34,154 - DEBUG - font_manager - findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=12.0 to DejaVu Sans ('C:\\Users\\marie\\Anaconda3\\envs\\logic\\lib\\site-packages\\matplotlib\\mpl-data\\fonts\\ttf\\DejaVuSans.ttf') with score of 0.050000.
2019-11-08 14:13:34,177 - DEBUG - _base - update_title_pos
2019-11-08 14:13:34,295 - DEBUG - _base - update_title_pos
2019-11-08 14:13:34,370 - DEBUG - _base - update_title_pos
2019-11-08 14:13:34,477 - DEBUG - _base - update_title_pos
2019-11-08 14:13:34,553 - DEBUG - _base - update_title_pos
2019-11-08 14:13:34,588 - DEBUG - _base - update_title_pos
2019-11-08 14:13:34,720 - DEBUG - _base - update_title_pos
2019-11-08 14:13:35,394 - DEBUG - _base - update_title_pos
2019-11-08 14:13:35,464 - DEBUG - _base - update_title_pos
2019-11-08 14:13:35,534 - DEBUG - _base - update_title_pos
2019-11-08 14:13:35,567 - DEBUG - _base - update_title_pos
2019-11-08 14:13:35,626 - DEBUG - _base - update_title_pos
2019-11-08 14:13:35,658 - DEBUG - _base - update_title_pos
2019-11-08 14:13:35,693 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:35] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 404 -
2019-11-08 14:13:35,702 - DEBUG - _base - update_title_pos
2019-11-08 14:13:35,762 - DEBUG - _base - update_title_pos
2019-11-08 14:13:35,928 - DEBUG - G4_output_functions - Saving flows storage.
2019-11-08 14:13:35,928 - DEBUG - G3a_economic_evaluation - Economic evaluation. Calculating investment costs over analysed timeframe.
2019-11-08 14:13:35,928 - DEBUG - G3a_economic_evaluation - Economic evaluation. Calculating O&M costs over analysed timeframe.
2019-11-08 14:13:35,928 - DEBUG - G3a_economic_evaluation - Economic evaluation. Scaling investment costs and O&M to year.
2019-11-08 14:13:35,928 - DEBUG - G3a_economic_evaluation - Economic evaluation. Calculating present costs.
2019-11-08 14:13:35,928 - DEBUG - G3a_economic_evaluation - Economic evaluation. Calculating fuel consumption and expenditures.
2019-11-08 14:13:35,928 - DEBUG - G3a_economic_evaluation - Economic evaluation. Calculating shortage and expenditures.
2019-11-08 14:13:35,928 - DEBUG - G3a_economic_evaluation - Economic evaluation. Calculating main grid consumption and expenditures.
2019-11-08 14:13:35,928 - DEBUG - G3a_economic_evaluation - Economic evaluation. Calculating feeding and revenues.
2019-11-08 14:13:35,928 - INFO - G0_oemof_simulate - Simulation of case "hoevelaken" resulted in : 
                  0.208 currency/kWh, at a renewable share of 52.42 percent with a reliability of 100.0 percent
2019-11-08 14:13:35,928 - INFO - G0_oemof_simulate -     Initial simulation time (s): 18.35 / Actual evaluation time (s): 82.21
2019-11-08 14:13:35,943 - DEBUG - G0_oemof_simulate -     Exact OEM results of case "hoevelaken" : 
                  0 kWh battery, 31.964 kWp PV, 100.597 kW wind, 44.37 kW genset at a renewable share of 52.42 percent with a reliability of 100.0 percent
2019-11-08 14:13:35,943 - DEBUG - G0_oemof_simulate -     Simulation of case hoevelaken complete.
2019-11-08 14:13:35,943 - DEBUG - G0_oemof_simulate - 

2019-11-08 14:13:36,222 - INFO - A_offgridders_wrapper -     Estimated simulation time left: 0.0 minutes.
2019-11-08 14:13:36,225 - INFO - A_offgridders_wrapper - 
 Simulation complete. Resulting parameters saved in "results.csv". 
 Overview over results:
2019-11-08 14:13:38,780 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:38] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 500 -
2019-11-08 14:13:38,857 - ERROR - _internal - Error on request:
Traceback (most recent call last):
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2111, in make_response
    rv = jsonify(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type int64 is not JSON serializable
2019-11-08 14:13:41,829 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:41] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 500 -
2019-11-08 14:13:41,844 - ERROR - _internal - Error on request:
Traceback (most recent call last):
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2111, in make_response
    rv = jsonify(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type int64 is not JSON serializable
2019-11-08 14:13:44,901 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:44] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 500 -
2019-11-08 14:13:44,915 - ERROR - _internal - Error on request:
Traceback (most recent call last):
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2111, in make_response
    rv = jsonify(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type int64 is not JSON serializable
2019-11-08 14:13:47,965 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:47] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 500 -
2019-11-08 14:13:47,996 - ERROR - _internal - Error on request:
Traceback (most recent call last):
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2111, in make_response
    rv = jsonify(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type int64 is not JSON serializable
2019-11-08 14:13:51,039 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:51] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 500 -
2019-11-08 14:13:51,055 - ERROR - _internal - Error on request:
Traceback (most recent call last):
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2111, in make_response
    rv = jsonify(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type int64 is not JSON serializable
2019-11-08 14:13:54,151 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:54] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 500 -
2019-11-08 14:13:54,162 - ERROR - _internal - Error on request:
Traceback (most recent call last):
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2111, in make_response
    rv = jsonify(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type int64 is not JSON serializable
2019-11-08 14:13:57,210 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:13:57] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 500 -
2019-11-08 14:13:57,223 - ERROR - _internal - Error on request:
Traceback (most recent call last):
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2111, in make_response
    rv = jsonify(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type int64 is not JSON serializable
2019-11-08 14:14:00,280 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:14:00] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 500 -
2019-11-08 14:14:00,296 - ERROR - _internal - Error on request:
Traceback (most recent call last):
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2111, in make_response
    rv = jsonify(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type int64 is not JSON serializable
2019-11-08 14:14:03,328 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:14:03] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 500 -
2019-11-08 14:14:03,328 - ERROR - _internal - Error on request:
Traceback (most recent call last):
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2111, in make_response
    rv = jsonify(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type int64 is not JSON serializable
2019-11-08 14:14:06,423 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:14:06] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 500 -
2019-11-08 14:14:06,423 - ERROR - _internal - Error on request:
Traceback (most recent call last):
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2111, in make_response
    rv = jsonify(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type int64 is not JSON serializable
2019-11-08 14:14:09,486 - INFO - _internal - 127.0.0.1 - - [08/Nov/2019 14:14:09] "GET /offgrid_simulator/get_result/20191108131148 HTTP/1.1" 500 -
2019-11-08 14:14:09,501 - ERROR - _internal - Error on request:
Traceback (most recent call last):
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\werkzeug\serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\app.py", line 2111, in make_response
    rv = jsonify(rv)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Users\marie\Anaconda3\envs\logic\lib\site-packages\simplejson\encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type int64 is not JSON serializable
